### ISSUE TITLE
Can not installed the library within Flex Builder

### ISSUE THREAD

**Issue by thipages** [DaVikingCode/ZBar-ANE#1]
Hi,
I have tried to install the library either the swc or the ane one and I got an error saying: error in catalog.xml. can you help. I am using FB4.7. Thanks

**Comment by alamboley** [comment]
Hey,
Which AIR SDK version are you using? Try to use AIR 14.

**Comment by thipages** [comment]
I am using sdk 4.6

**Comment by alamboley** [comment]
This is the flex sdk, and its air version is way too old. You have to update to latest AIR SDK.

**Comment by thipages** [comment]
ok, I am trying to install  the 14.0.0.178 air version in FB. Seems not so easy :-(

**Comment by thipages** [comment]
I have installed it according to http://helpx.adobe.com/flash-builder/kb/overlay-air-sdk-flash-builder.html 
and I have replace http://ns.adobe.com/air/application/3.4 by http://ns.adobe.com/air/application/14.0 in the -app.xml file

However got still the same error. Any ideas?

**Comment by alamboley** [comment]
Does your *-app.xml looks like `<application xmlns="http://ns.adobe.com/air/application/14.0">`

Also try to add to the compiler arguments: `swf-version=25`

**Comment by thipages** [comment]
Same error when adding -swf-version=25 to the compiler

The exact error (in french sorry) is "Erreur de fichier lors du traitement de catalog.xml dans C:\Users\tit_flash_lib\ZBar.swc(error in opening zip file)"

**Comment by thipages** [comment]
and my *-app.xml looks like <application xmlns="http://ns.adobe.com/air/application/14.0">

**Comment by alamboley** [comment]
Could you try removing the swc and using only the ANE file?

Have you ever worked with ANE?

**Comment by thipages** [comment]
Hi,
Yes I have already worked/installed ane file.
1. When I add it as .ane through the swc file addition interface, I have the same error
2. When I add it as .ane through the ane file addition interface, I have another error saying that the exetension.xml is absent or invalid.

**Comment by alamboley** [comment]
Could you please try with the https://github.com/DaVikingCode/ZXing-ANE ? It does everything that is supported by ZBar-ANE and more.

**Comment by thipages** [comment]
ok, I can not now, but I will in a couple of hours. Thanks

**Comment by thipages** [comment]
Hi,
I have exactly the same issue (same error messages) with the ZXing library as yours. Something wrong on my side....

**Comment by alamboley** [comment]
Yeah, I had no issue make it working with on FB 4.7

**Comment by thipages** [comment]
I cant find the issue.... If you could describe how you install it in a blank project within FB4.7, it may help me. Thanks!

**Comment by alamboley** [comment]
Have a look on my sample project: http://aymericlamboley.fr/test/ZXing-Ane.zip

**Comment by thipages** [comment]
I have imported the project (zip)
1. When I debug the project (android Platform), traces say "fail" (but the soft runs)
2. When I look at the ane reference, there is red error message saying that this ANE file does not support Windows Desktop Platform. Any ideas?

Thanks for your support/time

**Comment by alamboley** [comment]
1. Normally, you should have two messages, wikipedia url and the fail.
2. Yep because there isn't any specific case for windows, so it will run on the "default". Which in this ANE enables also QR Code recogition. Compiling in a simulator will use the "default". In fact every platform which are not iOS or Android will use the "default".

**Comment by thipages** [comment]
Hi, I tried pure AS3 version following http://polygeek.com/2011/11/06/moble-qr-code-app-using-actionscript/
The only change I did was to start a flex project and not an AS3 one.

Anyway it works. I will consolidate and keep you updated. Thanks

**Comment by alamboley** [comment]
The pure AS3 version will take you at least 5 seconds to decode, in native it's less than 1/2 seconds.
